name: Simple_Harvest
version: '${project.version}'
main: co.vangar.simple_harvest.Simple_harvest
api-version: 1.19
authors: [ Destined ]
description: A simple harvest and auto-plant plugin
website: https://vangar.co/
